version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Building the Lambda deployment package
      - zip -r lambda_deployment.zip .
artifacts:
  files:
    - lambda_deployment.zip
